name: Deploy to Azure - Production
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENNANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image
        uses: azure/docker-login@v2
        with:
          login-server: mtbracesdev.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        run: |
          docker build -t mtbracesdev.azurecr.io/switchback-frontend-prod:${{ github.sha }} .
          docker tag mtbracesdev.azurecr.io/switchback-frontend-prod:${{ github.sha }} mtbracesdev.azurecr.io/switchback-frontend-prod:latest
          docker push mtbracesdev.azurecr.io/switchback-frontend-prod:${{ github.sha }}
          docker push mtbracesdev.azurecr.io/switchback-frontend-prod:latest

      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: switchback-frontend-prod
          resourceGroup: switchback-prod
          imageToDeploy: mtbracesdev.azurecr.io/switchback-frontend-prod:${{ github.sha }}
